
CREATE SCHEMA IF NOT EXISTS built;
CREATE SCHEMA IF NOT EXISTS delineations;
CREATE SCHEMA IF NOT EXISTS energy;
CREATE SCHEMA IF NOT EXISTS grid_globals;
CREATE SCHEMA IF NOT EXISTS traffic;
CREATE SCHEMA IF NOT EXISTS tests;
CREATE SCHEMA IF NOT EXISTS user_input;
CREATE SCHEMA IF NOT EXISTS user_output;

CREATE SCHEMA IF NOT EXISTS aluejaot;
CREATE SCHEMA IF NOT EXISTS energia;
CREATE SCHEMA IF NOT EXISTS globals;
CREATE SCHEMA IF NOT EXISTS hiili;
CREATE SCHEMA IF NOT EXISTS liikenne;
CREATE SCHEMA IF NOT EXISTS rakymp;
